(env
 (_
  (flags
   (:standard -rectypes))))

(library
 (name numero_decls)
 (modules numero_decls)
 (libraries OCanren OCanren.tester counters)
 (preprocessor_deps %{project_root}/unif_count/pp5+dump.exe)
 ;
 (preprocess
  (pps
   OCanren-ppx.ppx_fresh
   --
   -pp
   "%{project_root}/unif_count/pp5+dump.exe")))

(library
 (name Quine_decls)
 (modules Quine_decls)
 (libraries OCanren OCanren.tester counters)
 (preprocessor_deps %{project_root}/unif_count/pp5+dump.exe)
 (preprocess
  (pps
   OCanren-ppx.ppx_fresh
   GT.ppx_all
   --
   -pp
   "%{project_root}/unif_count/pp5+dump.exe")))

(library
 (name Quines_NoDiseq)
 (modules Quines_NoDiseq)
 (libraries OCanren OCanren.tester)
 (preprocessor_deps %{project_root}/unif_count/pp5+dump.exe)
 (preprocess
  (pps
   OCanren-ppx.ppx_fresh
   GT.ppx_all
   --
   -pp
   "%{project_root}/unif_count/pp5+dump.exe")))

(library
 (name TimeHelper)
 (modules TimeHelper)
 (wrapped false)
 (libraries OCanren mtime.clock))

(executable
 (name test001_expo1)
 ;(public_name -)
 (modules test001_expo1)
 (libraries numero_decls TimeHelper))

(executable
 (name test002_logo1)
 (modules test002_logo1)
 (libraries numero_decls TimeHelper))

(executable
 (name test005_thrines)
 (modules test005_thrines)
 (libraries Quine_decls TimeHelper))

(executable
 (name test006_twines)
 (modules test006_twines)
 (libraries Quine_decls TimeHelper))

(executable
 (name test007_quines)
 (modules test007_quines)
 (libraries Quine_decls TimeHelper))

(executable
 (name test011_quinesNoDiseq)
 (modules test011_quinesNoDiseq)
 (libraries Quines_NoDiseq TimeHelper))

(rule
 (deps
  test001_expo1.exe
  test002_logo1.exe
  test005_thrines.exe
  test006_twines.exe
  test007_quines.exe
  test011_quinesNoDiseq.exe)
 (alias all_tests)
 (action
  (run echo)))
