(include "../faster-miniKanren/mk-vicare.scm")
(include "../faster-miniKanren/mk.scm")

(include "q.scm")
(include "list-display.scm")

; quines
(list-display
  (myrun1 1 (q)
    (fresh (temp q1)
      (== q1
              '(seq ((seq ((symb 'lambda)
                          (seq ((symb temp)))
                          (seq ((symb 'list)
                                ;(symb temp)
                                ;(seq  ( ('symb 'list)
                                ;        (seq ( (symb 'quote)
                                ;               (symb 'quote)))
                                ;        ;('symb temp)
                                ;      )
                                ;)
                                ))))
                    (seq ((symb 'quote)
                          (seq ((symb 'lambda)
                                ;(seq ((symb temp)))
                                ;(seq ((symb 'list)
                                ;      (symb temp)
                                ;      (seq ((symb 'list)
                                ;            (seq  ( (symb 'quote)
                                ;                    (symb 'quote)
                                ;                  ))
                                ;            (symb temp)))))
                                            ))))
                    )) )
      (eval-expo q1 '() `(val_ ,q))
    )
))

;(report_counters)
