(include "../faster-miniKanren/mk-vicare.scm")
(include "../faster-miniKanren/mk.scm")

(include "list-display.scm")

(define substo (lambda (in_ x newval rez)
  (conde
    ((fresh (y)
        (=== in_ `(v ,y))
        (=== y x)
        (=== rez newval)
      ))
    ((fresh (m n m2 n2)
      (=== in_ `(app ,m ,n))
      (=== rez `(app ,m2 ,n2))
      (substo m x newval m2)
      (substo n x newval n2)
    ))
    ((fresh (v b)
      (=== in_ `(abs ,v ,b))
      (conde
        ( (=== x v) (=== rez in_))
        ((fresh (b2)
          (=== rez `(abs ,v ,b2))
          (substo b x newval b2)
        ))
      )
    ))
  )
))

(define evalo (lambda (m n)
  (conde
    ((fresh (x)
        (=== m `(v ,x))
        (=== n m)
    ))
    ((fresh (x l)
        (=== m `(abs ,x ,l) )
        (=== n m)
    ))
    ;
    ((fresh (f a f2 a2)
        (=== m `(app ,f ,a))
        (evalo f f2)
        (evalo a a2)
        (lookupo s env r)
        (conde
          ((fresh (x l l2)
            (=== f2 `(abs ,x ,l)) (substo l x a2 l2) (evalo l2 n)
          ))
          ((fresh (p q)
            (=== f2 `(app ,p ,q)) (=== n `(app f2 a2))
          ))
          ((fresh (x)
            (=== f2 `(v ,x)) (=== n `(app f2 a2))
          ))
        )
    ))
  )
))

(define quine (lambda (q)
  (fresh (l r)
    (=== q `(app ,l ,r))
    (evalo q q)
  )
))

(define do_measure (lambda ()
  (run 1 (q2)
    (fresh (l r)
      (=== q2 `(app ,l ,r))
      (evalo q2 q2)
  ))
))

(list-display (do_measure))
(report_counters)
(exit)
